### ISSUE TITLE
运行的时候报错

### ISSUE THREAD

**Issue by xiaoshuoyiyi** [funnyzak/libreoffice-server#5]
运行的时候报这个错误，是什么原因呢？
D:\work\code\officeServer\node_modules\rimraf\rimraf.js:310
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\3248\AppData\Local\Temp\libreofficeConvert_-15744-PZdz1QfxtMfu'
    at Object.rmdirSync (fs.js:916:10)
    at rmkidsSync (D:\work\code\officeServer\node_modules\rimraf\rimraf.js:349:27)
    at rmdirSync (D:\work\code\officeServer\node_modules\rimraf\rimraf.js:329:7)
    at rimrafSync (D:\work\code\officeServer\node_modules\rimraf\rimraf.js:301:9)
    at Object._cleanupCallback [as removeCallback] (D:\work\code\officeServer\node_modules\tmp\lib\tmp.js:356:16)
    at D:\work\code\officeServer\node_modules\libreoffice-convert\index.js:63:17
    at wrapper (D:\work\code\officeServer\node_modules\async\dist\async.js:271:20)
    at D:\work\code\officeServer\node_modules\async\dist\async.js:1143:21
    at D:\work\code\officeServer\node_modules\async\dist\async.js:327:20
    at D:\work\code\officeServer\node_modules\libreoffice-convert\index.js:39:32
    at D:\work\code\officeServer\node_modules\async\dist\async.js:2965:13
    at wrapper (D:\work\code\officeServer\node_modules\async\dist\async.js:271:20)
    at iteratorCallback (D:\work\code\officeServer\node_modules\async\dist\async.js:501:17)
    at D:\work\code\officeServer\node_modules\async\dist\async.js:327:20
    at D:\work\code\officeServer\node_modules\async\dist\async.js:2957:17
    at D:\work\code\officeServer\node_modules\libreoffice-convert\index.js:36:68 {
  errno: -4051,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'C:\\Users\\zzb\AppData\\Local\\Temp\\libreofficeConvert_-15744-PZdz1QfxtMfu'
}

**Comment by funnyzak** [comment]
先手动删除项目下 `node_modules` 目录，然后`npm ci`，再启动试一试。

**Comment by xiaoshuoyiyi** [comment]
刚试了下，还是有同样的问题

**Comment by funnyzak** [comment]
按提示手动删除下 `C:\Users\zzb\AppData\Local\Temp\libreofficeConvert-15744-PZdz1QfxtMfu` 此目录试试。Node用 `V16`

**Comment by xiaoshuoyiyi** [comment]
用了这个方法还是不行，最后把liboffice安装目录放到C盘就可以了！

**Comment by funnyzak** [comment]
👌
